const MARDEK = {
	Chapter1: {
		Image: "Chapter1",
		Mardek: {
			Image:"kidMardek",
			Name:"KidMardek",
			Skills:[
				{Type: "Imagination", Name: "Strike", Found: "Stick", Total: 5},
				{Type: "Imagination", Name: "Huff-Puff", Found: "Tunic", Total: 5},
				{Type: "PhysAtk", Name: "DMG+1", Found: "Stick", Total: 5},
				{Type: "PhysDef", Name: "Block", Found: "Stick", Total: 5},
				{Type: "Passive", Name: "Insomnia", Found: "Cog necklace (reaction doesn't carry over to CH2)", Total: 20}
			]
		},
		Deugan: {
			Image:"kidDeugan",
			Name:"KidDeugan",
			Skills:[
				{Type: "Imagination", Name: "Strike", Found: "Big Stick", Total: 5},
				{Type: "Imagination", Name: "Huff-Puff", Found: "Tunic", Total: 5},
				{Type: "PhysAtk", Name: "DMG+1", Found: "Big Stick", Total: 5},
				{Type: "PhysDef", Name: "Block", Found: "Big Stick", Total: 5},
				{Type: "Passive", Name: "Insomnia", Found: "Cog necklace (reaction doesn't carry over to CH2)",  Total: 20}
			]
		}
	},
	Chapter2: {
		Image: "Chapter2",
        Mardek: {
			Image:"guardMardek",
			Name:"Mardek",
			Skills:[
				{Type: "MagicSword", Name: "Heal", Found: "Starting Skill", Total: 0},
				{Type: "MagicSword", Name: "Remove Taint", Found: "Snakestone", Total: 5},
				{Type: "MagicSword", Name: "Shield", Found: "MoonstoneRing", Total: 20},
				{Type: "MagicSword", Name: "M. Shield", Found: "Lapis Lily", Total: 20},
				{Type: "MagicSword", Name: "Warp", Found: "Starting Skill", Total: 0},
				{Type: "PhysAtk",  Name: "DMG+10%", Found: "Iron Sword, Mace", Total: 10},
				{Type: "PhysAtk",  Name: "DMG+20%", Found: "Longsword", Total: 20},
				{Type: "PhysAtk",  Name: "DMG+30%", Found: "Champion Sword", Total: 30},
				{Type: "PhysAtk",  Name: "Quarry: UNDEAD", Found: "Silver Sword", Total: 20},
				{Type: "PhysAtk",  Name: "Degeneration", Found: "ShadowBlade", Total: 40},
				{Type: "PhysDef",  Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail", Total: 10},
				{Type: "PhysDef",  Name:  "DMG-20%", Found: "Chainmail, Copper Breastplate", Total: 20},
				{Type: "PhysDef",  Name:  "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Total: 10},
				{Type: "PhysDef",  Name:  "DMG Soak 20", Found: "Breastplate", Total: 15},
				{Type: "PhysDef",  Name:  "Evasion 20%", Found: "Bandit Leather", Total: 20},
				{Type: "MagDef",  Name:  "M DMG-10%", Found: "Green Chainmail", Total: 10},
				{Type: "MagDef",  Name:  "M FIRE-50%", Found: "FirePendant", Total: 25},
				{Type: "Passive",  Name:  "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive",  Name:  "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive",  Name:  "Antibody", Found: "Snakestone", Total: 20},
				{Type: "Passive",  Name:  "Insomnia", Found: "Cog Necklace, MoonstoneRing", Total: 20},
				{Type: "Passive",  Name:  "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive",  Name:  "Bright Eyes", Found: "OnyxRing", Total: 20},
				{Type: "Passive",  Name:  "Purity", Found: "Bonemail", Total: 20},
				{Type: "Passive",  Name:  "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive",  Name:  "AGL+1", Found: "Bandit Leather", Total: 15},
				{Type: "Passive",  Name:  "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive",  Name:  "Resist EARTH", Found: "GeoJacket", Total: 50}
			]
		},
		Deugan: {
			Image:"Deugan",
			Name:"Deugan",
			Skills:[
				{Type: "Spellbladery", Name: "Power Attack", Found: "Greatsword, Mythril Greatblade", Total: 20},
				{Type: "Spellbladery", Name: "Earth Slash", Found: "Tectonic Sword", Total: 10},
				{Type: "Spellbladery", Name: "Boost", Found: "Burial Sword", Total: 20},
				{Type: "Spellbladery", Name: "Barrier Break", Found: "Iron Greatblade", Total: 10},
				{Type: "Spellbladery", Name: "Spiritblade", Found: "Ancient Sword", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Greatsword", Total: 20},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Burial Sword", Total: 30},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Green Chainmail", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate", Total: 20},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate", Total: 15},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Ancient Sword", Total: 20},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Total: 25},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Total: 15},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50}
			]
		},
		Emela: {
			Image:"Emela",
			Name:"Emela",
			Skills:[
				{Type: "Elemancy", Name: "Flame", Found: "Fire Rod", Total: 20},
				{Type: "Elemancy", Name: "Lightning Bolt", Found: "Starting Skill", Total: 0},
				{Type: "Elemancy", Name: "Stonesplosion", Found: "Earth Rod", Total: 20},
				{Type: "Elemancy", Name: "Bubble", Found: "Water Rod", Total: 20},
				{Type: "Elemancy", Name: "Aqualung", Found: "Starting Skill", Total: 0},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Starting Skill", Total: 0},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour", Total: 15},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Lightning Rod", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Water Rod", Total: 20},
				{Type: "MagAtk", Name: "M+Poison 20%", Found: "Earth Rod", Total: 20},
				{Type: "MagAtk", Name: "M+Stun 20%", Found: "Lightning Rod", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe", Total: 20},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Total: 30},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Total: 25},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Total: 15},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50}
			]
		},
		Vehrn: {
			Image:"Vehrn",
			Name:"Vehrn",
			Skills:[
				{Type: "HolyArts", Name: "Smite Evil", Found: "Bronze Sword", Total: 20},
				{Type: "HolyArts", Name: "Disrupt Undead", Found: "Silver Sword", Total: 20},
				{Type: "HolyArts", Name: "Green Lightning", Found: "YalortianAmulet", Total: 20},
				{Type: "PhysAtk", Name: "Smite+", Found: "Bronze Sword", Total: 20},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Iron Sword, Mace", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Longsword", Total: 20},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Champion Sword", Total: 30},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Sword", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration", Found: "ShadowBlade", Total: 40},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate", Total: 20},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate", Total: 15},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Total: 25},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Total: 15},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50}
			]
		},
		Zach: {
			Image:"Zach",
			Name:"Zach",
			Skills:[
				{Type: "Techniques", Name: "Berserk", Found: "Shashiik", Total: 10},
				{Type: "Techniques", Name: "Crescendo Slash", Found: "Boneslicer", Total: 20},
				{Type: "Techniques", Name: "Sure Slash", Found: "Twin Trilobites", Total: 20},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Shashiik", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Shashiik", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Boneslicer", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: INSECT", Found: "Twin Trilobites", Total: 20},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Green Chainmail", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate", Total: 20},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate", Total: 15},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant", Total: 25},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather", Total: 15},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50}
			]
		}
	},
    Chapter3: {
		Image: "Chapter3",
		Mardek: {
			Image:"knightMardek",
			Name:"Mardek",
			Skills:[
				{Type: "MagicSword", Name: "Heal", Found: "Starting Skill", Total: 0},
				{Type: "MagicSword", Name: "Regen", Found: "Moonstone", Total: 20},
				{Type: "MagicSword", Name: "Remove Taint", Found: "Snakestone", Total: 5},
				{Type: "MagicSword", Name: "Remove Evil", Found: "M Charm", Total: 15},
				{Type: "MagicSword", Name: "Shield", Found: "MoonstoneRing, Gold Shield", Total: 20},
				{Type: "MagicSword", Name: "M. Shield", Found: "Lapis Lily, Rune Shield, Rune Shield +", Total: 20},
				{Type: "MagicSword", Name: "Morality Block", Found: "Bronze Armour, Solakian Platemail", Total: 10},
				{Type: "MagicSword", Name: "Fire Slash", Found: "Flametongue", Total: 20},
				{Type: "MagicSword", Name: "Water Slash", Found: "Fishslayer", Total: 20},
				{Type: "MagicSword", Name: "Air Slash", Found: "Aeropolitan Scimitar", Total: 20},
				{Type: "MagicSword", Name: "Earth Slash", Found: "Forest Edge", Total: 20},
				{Type: "MagicSword", Name: "Warp", Found: "Starting Skill", Total: 0},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Iron Sword, Mace, Mythril Sword", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Longsword, Sun Sword", Total: 20},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Champion Sword, Champion Sword II", Total: 30},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Xantusian Scimitar", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Champion Sword II", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Sword", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "ShadowBlade, Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "Blood Sword, BloodOpal", Total: 10},
				{Type: "PhysAtk", Name: "P+Bleed 20%", Found: "Cursed Blade", Total: 20},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail, SilverRing", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate, Spiked Hide Armour", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Iron Armour, Mythril Platemail, Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate, Gold Shield, Spiked Hide Armour", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole, Mythril Platemail", Total: 20},
				{Type: "PhysDef", Name: "AIR-50%", Found: "Wing Shield", Total: 25},
				{Type: "PhysDef", Name: "LIGHT-50%", Found: "Shield of Light, Solakian Platemail", Total: 25},
				{Type: "PhysDef", Name: "DARK-50%", Found: "Shield of Darkness", Total: 25},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest, Golden M Helm", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Rune Shield, Turquoise Armour", Total: 20},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M DMG Soak 20", Found: "Rune Shield +", Total: 15},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "Wing Shield, AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M LIGHT-50%", Found: "Shield of Light", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Shield of Darkness, Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Glyph Shield", Total: 30},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, Golden M Helmet, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Total: 50},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 10},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Donovan: {
			Image:"Donovan",
			Name:"Donovan",
			Skills:[
				{Type: "Pyromancy", Name: "Flame", Found: "Ember Spear", Total: 10},
				{Type: "Pyromancy", Name: "Blaze", Found: "Firefang", Total: 30},
				{Type: "Pyromancy", Name: "Burn", Found: "Desert Spear", Total: 20},
				{Type: "Pyromancy", Name: "Null Fire Once", Found: "Firestone Ring, Firefang", Total: 10},
				{Type: "Pyromancy", Name: "Remove Numbness", Found: "Iron Spear", Total: 5},
				{Type: "Pyromancy", Name: "Pyro Shell", Found: "Obelisk", Total: 10},
				{Type: "Pyromancy", Name: "Strength Boost", Found: "Dragonblood Charm", Total: 10},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Stingstick", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Firefang", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Ember Spear, Wing Spear", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysAtk", Name: "P+Poison 20%", Found: "Stingstick", Total: 20},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Snakemail, GoldRing Gauntlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Leather", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Magic Poker, Feather Crest", Total: 20},
				{Type: "MagAtk", Name: "M FIRE+20%", Found: "Ember Spear", Total: 20},
				{Type: "MagAtk", Name: "M AIR+20%", Found: "Wing Spear", Total: 20},
				{Type: "MagAtk", Name: "M+Numb 20%", Found: "Ember Charm", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe", Total: 20},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Total: 30},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Total: 30},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Sharla: {
			Image:"Sharla",
			Name:"Sharla",
			Skills:[
				{Type: "Aeromancy", Name: "Lightning Bolt", Found: "Wing Spear", Total: 10},
				{Type: "Aeromancy", Name: "Thunderbolt", Found: "Magic Poker", Total: 30},
				{Type: "Aeromancy", Name: "Healing Wind", Found: "Topaz", Total: 20},
				{Type: "Aeromancy", Name: "Null Air Once", Found: "Iron Spear", Total: 10},
				{Type: "Aeromancy", Name: "Remove Paralysis", Found: "Iron Spear", Total: 5},
				{Type: "Aeromancy", Name: "Aero Shell", Found: "Obelisk", Total: 10},
				{Type: "Aeromancy", Name: "Gust Shield", Found: "Desert Spear", Total: 10},
				{Type: "Aeromancy", Name: "Agility Boost", Found: "Boots of Celerity", Total: 10},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Stingstick", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Firefang", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Ember Spear, Wing Spear", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysAtk", Name: "P+Poison 20%", Found: "Stingstick", Total: 20},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Snakemail, GoldRing Gauntlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Leather", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Magic Poker, Feather Crest", Total: 20},
				{Type: "MagAtk", Name: "M FIRE+20%", Found: "Ember Spear", Total: 20},
				{Type: "MagAtk", Name: "M AIR+20%", Found: "Wing Spear", Total: 20},
				{Type: "MagAtk", Name: "M+Stun 20%", Found: "Feather Charm", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe", Total: 20},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Total: 30},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Total: 30},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Sslenck: {
			Image:"Sslen'ck",
			Name:"Sslen'ck",
			Skills:[
				{Type: "DragonTech", Name: "Fire Breath", Found: "Starting Skill", Total: 0},
				{Type: "DragonTech", Name: "Fire Stream", Found: "Drackal Crescent", Total: 10},
				{Type: "DragonTech", Name: "Perforate", Found: "Bone Axe", Total: 20},
				{Type: "DragonTech", Name: "Boost", Found: "Mighty Axe", Total: 20},
				{Type: "DragonTech", Name: "Earth Slash", Found: "Stone Axe", Total: 10},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Greataxe", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Sun Axe, Iron Axe", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Drackal Crescent", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: BEAST", Found: "Bone Axe", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: DRAGON", Found: "Drackal Crescent", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Axe", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: HUMAN", Found: "Iron  Axe", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: INSECT", Found: "Mighty Axe", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Leather Armour, Green Chainmail, Bronze Circlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Chainmail, Copper Breastplate", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Iron Armour, Mythril Armour, Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour, Breastplate", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole, Mythril Armour", Total: 20},
				{Type: "PhysDef", Name: "LIGHT-50%", Found: "Solakian Platemail", Total: 25},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "Passive", Name: "Dragon's Blood", Found: "Starting Skill", Total: 0},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Total: 50},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Solaar: {
			Image:"Solaar",
			Name:"Solaar",
			Skills:[
				{Type: "AstralMagic", Name: "Solar Flare", Found: "Starting Skill", Total: 0},
				{Type: "AstralMagic", Name: "Galaxy Burst", Found: "Guardian Claw", Total: 10},
				{Type: "AstralMagic", Name: "Pleasant Sunbeam", Found: "Starting Skill", Total: 0},
				{Type: "AstralMagic", Name: "Resurrect", Found: "Eclipse Amulet", Total: 10},
				{Type: "AstralMagic", Name: "Spirit Graft", Found: "Turquoise", Total: 10},
				{Type: "AstralMagic", Name: "Purity", Found: "Viper Claw", Total: 15},
				{Type: "AstralMagic", Name: "Astral Form", Found: "SoulStone", Total: 10},
				{Type: "AstralMagic", Name: "Luncatic Howl", Found: "Star Charm", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Raptor Claw", Total: 20},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Raptor Claw", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Claw", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysAtk", Name: "P+Poison 20%", Found: "Viper Claw", Total: 20},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Bronze Circlet, Gauntlet, SilverRing", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Silver Claw, Feather Crest", Total: 20},
				{Type: "MagAtk", Name: "M DMG+30%", Found: "Guardian Claw", Total: 30},
				{Type: "MagAtk", Name: "M LIGHT+20%", Found: "Guardian Claw", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Elwyen: {
			Image:"Elwyen",
			Name:"Elwyen",
			Skills:[
				{Type: "SirenSongs", Name: "Spirit Song", Found: "Sheet Music I", Total: 20},
				{Type: "SirenSongs", Name: "Vigorous March", Found: "Sheet Music II", Total: 20},
				{Type: "SirenSongs", Name: "Solid Sonata", Found: "Sheet Music III", Total: 20},
				{Type: "SirenSongs", Name: "Runic Rhapsody", Found: "Sheet Music IV", Total: 20},
				{Type: "SirenSongs", Name: "Dolorous Dirge", Found: "Sheet Music V", Total: 20},
				{Type: "SirenSongs", Name: "Requiem", Found: "Sheet Music VI", Total: 10},
				{Type: "SirenSongs", Name: "Ballad of Life", Found: "Sheet Music VII", Total: 20},
				{Type: "SirenSongs", Name: "Ballad of Balance", Found: "Sheet Music VIII", Total: 20},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Silver Harp", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Fairy Harp", Total: 20},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Astral Harp", Total: 30},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Wave Harp", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Magic Blouse, Leather Armour, Bronze Circlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "WATER-50%", Found: "Wave Harp", Total: 25},
				{Type: "PhysDef", Name: "EARTH-50%", Found: "Fairy Harp", Total: 25},
				{Type: "PhysDef", Name: "DARK-50%", Found: "Silver Harp", Total: 25},
				{Type: "PhysDef", Name: "AETHER-50%", Found: "Astral Harp", Total: 25},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "PhysDef", Name: "Evasion 50%", Found: "Lapis Beads", Total: 50},
				{Type: "PhysDef", Name: "Survivor", Found: "Minstrel's Tiara", Total: 40},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens (Elwyen cannot master this skill)", Total: -1},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest (Elwyen cannot master this skill)", Total: -1},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe, Shaman's Vestment", Total: 20},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Total: 30},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Total: 30},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist EARTH", Found: "Geojacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise, Astral Wanderer's Garb", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope, Astral Harp", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Gloria: {
			Image:"Gloria",
			Name:"Gloria",
			Skills:[
				{Type: "NatureMagic", Name: "Wildfire", Found: "FireOpal, Fire Staff", Total: 20},
				{Type: "NatureMagic", Name: "Whirlpool", Found: "Aquamarine, Trilobite Staff", Total: 20},
				{Type: "NatureMagic", Name: "Twister", Found: "Topaz, Air Staff", Total: 20},
				{Type: "NatureMagic", Name: "Razor Leaf", Found: "Jade, Earth Staff", Total: 20},
				{Type: "NatureMagic", Name: "Earth Heal", Found: "Earth Staff", Total: 10},
				{Type: "NatureMagic", Name: "Barkskin", Found: "Emerald Bangle", Total: 10},
				{Type: "NatureMagic", Name: "Cleanse", Found: "Leaf Charm", Total: 30},
				{Type: "NatureMagic", Name: "Mass Cleanse", Found: "Yggdrasil's Finger", Total: 15},
				{Type: "NatureMagic", Name: "Null Fire Once", Found: "Fire Staff", Total: 10},
				{Type: "NatureMagic", Name: "Null Water Once", Found: "Sapphire Bangle, Trilobite Staff", Total: 10},
				{Type: "NatureMagic", Name: "Null Air Once", Found: "Air Staff", Total: 10},
				{Type: "NatureMagic", Name: "Null Earth Once", Found: "GreenBeads", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Polemace, Fire Staff", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Earth Staff", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Magic Blouse, Leather Armour, Bronze Circlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Stole, Magic Shirt, Inventing Coat", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Air Staff, Feather Crest", Total: 20},
				{Type: "MagAtk", Name: "M DMG+30%", Found: "Yggdrasil's Finger", Total: 30},
				{Type: "MagAtk", Name: "M Drain HP 10%", Found: "Mahogany Staff", Total: 10},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Jasper Robe, Shaman's Vestment", Total: 20},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Total: 30},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Total: 30},
				{Type: "Passive", Name: "Nature's Favour", Found: "Shaman's Vestment", Total: 5},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist EARTH", Found: "Geojacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise, Astral Wanderer's Garb", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Meraeador: {
			Image:"Meraeador",
			Name:"Meraeador",
			Skills:[
				{Type: "Inventions", Name: "Thermal Spanner", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Silver Mirror", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Golden Mirror", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Flamethrower", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Gas-O-Matic", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Sleep-O-Matic", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Potion Spray", Found: "Cannot be mastered", Total: -1},
				{Type: "Inventions", Name: "Drill-O-Matic", Found: "Cannot be mastered", Total: -1},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Leather Armour, Bronze Circlet, Gauntlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Inventing Coat, Steel Stole, Magic Shirt", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Reinforced Armour", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Mage Robe, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Hempen Robe, Japser Robe, Shaman's Vestment", Total: 20},
				{Type: "MagDef", Name: "M DMG-30%", Found: "Green Robe", Total: 30},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Dark Robe", Total: 30},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Stole +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist EARTH", Found: "Geojacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise, Astral Wanderer's Garb", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Vehrn: {
			Image:"Vehrn",
			Name:"Vehrn",
			Skills:[
				{Type: "HolyArts", Name: "Smite Evil", Found: "Bronze Sword", Total: 20},
				{Type: "HolyArts", Name: "Disrupt Undead", Found: "Silver Sword", Total: 20},
				{Type: "HolyArts", Name: "Divine Glory", Found: "Righteous Justice", Total: 30},
				{Type: "HolyArts", Name: "Lay on Hands", Found: "Righteous Honour", Total: 20},
				{Type: "HolyArts", Name: "Green Lightning", Found: "YalortianAmulet", Total: 20},
				{Type: "HolyArts", Name: "Emerald Shock", Found: "YALORT Charm", Total: 20},
				{Type: "PhysAtk", Name: "Smite+", Found: "Bronze Sword, Clerical Mace", Total: 20},
				{Type: "PhysAtk", Name: "Smite X", Found: "Righteous Justice", Total: 20},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Iron Sword, Mace, Mythril Sword", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Longsword, Sun Sword", Total: 20},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Champion Sword, Champion Sword II", Total: 30},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Xantusian Scimitar", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Champion Sword II, Righteous Justice", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Silver Sword", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "ShadowBlade, Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "Blood Sword, BloodOpal", Total: 10},
				{Type: "PhysAtk", Name: "P+Bleed 20%", Found: "Cursed Blade", Total: 20},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Wooden Shield, Green Chainmail, SilverRing", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate, Righteous Honour", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Iron Armour, Mythril Platemail, Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Bronze Shield, Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Breastplate, Gold Shield, Spiked Hide Armour", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole, Mythril Platemail", Total: 20},
				{Type: "PhysDef", Name: "AIR-50%", Found: "Wing Shield", Total: 25},
				{Type: "PhysDef", Name: "LIGHT-50%", Found: "Shield of Light, Solakian Platemail", Total: 25},
				{Type: "PhysDef", Name: "DARK-50%", Found: "Shield of Darkness", Total: 25},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG-20%", Found: "Rune Shield, Righteous Honour", Total: 20},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M DMG Soak 20", Found: "Rune Shield +", Total: 15},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "Wing Shield, AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M LIGHT-50%", Found: "Shield of Light", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Shield of Darkness, Black Hat", Total: 25},
				{Type: "MagDef", Name: "Spell Resist: 30%", Found: "Glyph Shield", Total: 30},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Total: 50},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Zach: {
			Image:"Zach",
			Name:"Zach",
			Skills:[
				{Type: "Techniques", Name: "Berserk", Found: "Shashiik", Total: 10},
				{Type: "Techniques", Name: "Crescendo Slash", Found: "Boneslicer", Total: 20},
				{Type: "Techniques", Name: "Sure Slash", Found: "Twin Trilobites", Total: 20},
				{Type: "Techniques", Name: "Coup de Grace", Found: "Two Moons", Total: 10},
				{Type: "Techniques", Name: "Sinstrike", Found: "Snakemail", Total: 20},
				{Type: "Techniques", Name: "Immoral Injustice", Found: "Yin and Yang", Total: 20},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Shashiik", Total: 20},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Two Moons", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Scoping Lens", Total: 20},
				{Type: "PhysAtk", Name: "Soulstrike", Found: "Shashiik, Eagle Wings", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: UNDEAD", Found: "Boneslicer", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: INSECT", Found: "Twin Trilobites", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Green Chainmail, Snakemail, Gauntlet", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Chainmail, Copper Breastplate, Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Spiked Hide Armour, Skull Helm, Breastplate", Total: 15},
				{Type: "PhysDef", Name: "DMG Soak 30", Found: "Steel Stole", Total: 20},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Bandit Leather, Eclipse Amulet", Total: 20},
				{Type: "PhysDef", Name: "Evasion 50%", Found: "Yin and Yang", Total: 50},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens (Zach cannot master this skill)", Total: -1},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest (Zach cannot master this skill)", Total: -1},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Green Chainmail, Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "Passive", Name: "HP+10%", Found: "Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "MP+10%", Found: "Lapis Lily, Mind Crystal", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Snakemail, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Purity", Found: "Bonemail, Solakian Platemail, Yalortian Robe", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal, Scarlet Stole +2", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby, Scarlet Stole +4", Total: 30},
				{Type: "Passive", Name: "STR+3", Found: "Scarlet Stole +6", Total: 45},
				{Type: "Passive", Name: "VIT+1", Found: "Jade, Green Stole +2", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald, Green Stole +4", Total: 30},
				{Type: "Passive", Name: "VIT+3", Found: "Green Stole +6", Total: 45},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine, Azure Staff +2", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire, Azure Stole +4, Turquoise Armour", Total: 30},
				{Type: "Passive", Name: "SPR+3", Found: "Azure Stole +6", Total: 45},
				{Type: "Passive", Name: "AGL+1", Found: "Bandit Leather, Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity, Eagle Wings", Total: 30},
				{Type: "Passive", Name: "Resist FIRE", Found: "Flamemail", Total: 50},
				{Type: "Passive", Name: "Resist WATER", Found: "Trilobite Armour", Total: 50},
				{Type: "Passive", Name: "Resist EARTH", Found: "GeoJacket", Total: 50},
				{Type: "Passive", Name: "Resist DARK", Found: "Night Jacket", Total: 50},
				{Type: "Passive", Name: "Resist AETHER", Found: "Astral Wanderer's Garb, Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "LesserRainbowShirt, Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		},
		Legion: {
			Image:"Legion",
			Name:"Legion",
			Skills:[
				{Type: "Mimicry", Name: "Dark Claw", Found: "Drowned Corpse, Punk Monster, Forgotten Face", Total: 1},
				{Type: "Mimicry", Name: "Blood Claw", Found: "Red Dragon, Bone Demon, Annihilator:Karnos", Total: 1},
				{Type: "Mimicry", Name: "Money Attack!", Found: "Posh Gruul, Posh Zombie", Total: 1},
				{Type: "Mimicry", Name: "Blood Drain", Found: "Leech Bat, Albino Bat, Ghoul", Total: 1},
				{Type: "Mimicry", Name: "Gemsplosion", Found: "Moonstone, Fire Opal, Topaz", Total: 1},
				{Type: "Mimicry", Name: "Fire Breath", Found: "Lupaazr, Blood Lizard, Magmazard", Total: 1},
				{Type: "Mimicry", Name: "Bubble Breath", Found: "Angry Cod, Roaming Axolotl, Axolotl", Total: 1},
				{Type: "Mimicry", Name: "Curse", Found: "Green Soul, Pixie, Whim", Total: 1},
				{Type: "Mimicry", Name: "Addle Gas", Found: "Pixie, I-Orb Spawn, Chaosoul", Total: 1},
				{Type: "Mimicry", Name: "Revenge Strike", Found: "Centaur (Male)", Total: 1},
				{Type: "Mimicry", Name: "1000 Needles", Found: "Happy Johnny", Total: 1},
				{Type: "Mimicry", Name: "Rage Chord", Found: "Temperance (Fire), Pixie, Charred Bones", Total: 1},
				{Type: "Mimicry", Name: "Poison Sting", Found: "Wasp, Blade Bee, Poison Bee", Total: 1},
				{Type: "Mimicry", Name: "Spectral Touch", Found: "Forgotten Face, Apparition", Total: 1},
				{Type: "Mimicry", Name: "Ripping Slash", Found: "Brown Mantid, Green Mantid, Antlion", Total: 1},
				{Type: "Mimicry", Name: "Acid", Found: "Balloon, Ooze", Total: 1},
				{Type: "Mimicry", Name: "Morbid Fondle", Found: "Drowned Corpse, Ghoul, Ghast", Total: 1},
				{Type: "Mimicry", Name: "Viscous Ooze", Found: "Ooze, Waterdrop, Lava Blob", Total: 1},
				{Type: "Mimicry", Name: "Spirit Nova", Found: "Green Soul, Blue Soul, Chaosoul", Total: 1},
				{Type: "Mimicry", Name: "Sombre Tears", Found: "I-Orb, Blue Soul, Black Eye", Total: 1},
				{Type: "Mimicry", Name: "Needleflare", Found: "Happy Johnny", Total: 1},
				{Type: "Mimicry", Name: "Fairy Dust", Found: "Rogue Fairy", Total: 1},
				{Type: "Mimicry", Name: "Heavy Blow", Found: "Golem, Mythril Golem", Total: 1},
				{Type: "Mimicry", Name: "Raging Inferno", Found: "Fire Guardian, Bone Demon, Annihilator:Karnos", Total: 1},
				{Type: "Mimicry", Name: "Tsunami", Found: "Water Guardian, Annihilator:Karnos, King of Goznor", Total: 1},
				{Type: "Mimicry", Name: "Earthquake", Found: "Earth Guardian, Annihilator:Karnos, Bone Demon", Total: 1},
				{Type: "Mimicry", Name: "Thunderstorm", Found: "Temperance (Air), Bernard, Muriance", Total: 1},
				{Type: "PhysAtk", Name: "DMG+10%", Found: "Clasping Claws", Total: 10},
				{Type: "PhysAtk", Name: "DMG+20%", Found: "Hammerfist", Total: 20},
				{Type: "PhysAtk", Name: "DMG+30%", Found: "Buzzsaw Arm", Total: 30},
				{Type: "PhysAtk", Name: "Critical+20%", Found: "Buzzsaw Arm", Total: 20},
				{Type: "PhysAtk", Name: "Accuracy+50%", Found: "Clasping Claws", Total: 20},
				{Type: "PhysAtk", Name: "Quarry: SPIRIT", Found: "Wispstone", Total: 20},
				{Type: "PhysAtk", Name: "Shield Break 10%", Found: "Hammerfist", Total: 40},
				{Type: "PhysAtk", Name: "Degeneration 10%", Found: "Onyx", Total: 40},
				{Type: "PhysAtk", Name: "Drain HP 10%", Found: "BloodOpal", Total: 10},
				{Type: "PhysDef", Name: "DMG-10%", Found: "Copper Plating, SilverRing, GoldRing", Total: 10},
				{Type: "PhysDef", Name: "DMG-20%", Found: "Steel Plating", Total: 20},
				{Type: "PhysDef", Name: "DMG-30%", Found: "Titan Plating, Golden Gauntlet", Total: 30},
				{Type: "PhysDef", Name: "DMG Soak 10", Found: "Pickaxe Pendant", Total: 10},
				{Type: "PhysDef", Name: "DMG Soak 20", Found: "Skull Helm", Total: 15},
				{Type: "PhysDef", Name: "Evasion 20%", Found: "Eclipse Amulet", Total: 20},
				{Type: "MagAtk", Name: "M DMG+10%", Found: "Scoping Lens", Total: 10},
				{Type: "MagAtk", Name: "M DMG+20%", Found: "Feather Crest", Total: 20},
				{Type: "MagDef", Name: "M DMG-10%", Found: "Silver Circlet", Total: 10},
				{Type: "MagDef", Name: "M DMG Soak 10", Found: "Elf Cap", Total: 10},
				{Type: "MagDef", Name: "M FIRE-50%", Found: "FirePendant, Dragonblood Charm", Total: 25},
				{Type: "MagDef", Name: "M WATER-50%", Found: "WaterPendant", Total: 25},
				{Type: "MagDef", Name: "M AIR-50%", Found: "AirPendant", Total: 25},
				{Type: "MagDef", Name: "M EARTH-50%", Found: "EarthPendant", Total: 25},
				{Type: "MagDef", Name: "M DARK-50%", Found: "Black Hat", Total: 25},
				{Type: "Passive", Name: "Mechanical body", Found: "Starting Skill", Total: 0},
				{Type: "Passive", Name: "HP+10%", Found: "Copper Plating, Body Crystal", Total: 10},
				{Type: "Passive", Name: "HP+20%", Found: "Steel Plating, Emerald Bangle", Total: 20},
				{Type: "Passive", Name: "HP+30%", Found: "Titan Plating", Total: 30},
				{Type: "Passive", Name: "MP+10%", Found: "Mind Crystal, Lapis Lily", Total: 10},
				{Type: "Passive", Name: "MP+20%", Found: "Sapphire Bangle, SoulStone", Total: 20},
				{Type: "Passive", Name: "Antibody", Found: "Snakestone, Viper's Eye", Total: 20},
				{Type: "Passive", Name: "Loquacity", Found: "Sorcerer's Soul", Total: 20},
				{Type: "Passive", Name: "Suppleness", Found: "Dragonblood Charm, Warlord's Soul", Total: 20},
				{Type: "Passive", Name: "Insomnia", Found: "Cog Necklace, MoonstoneRing, Moonstone", Total: 20},
				{Type: "Passive", Name: "Clarity", Found: "Amethyst, Amethyst Earring", Total: 20},
				{Type: "Passive", Name: "Locomotion", Found: "Belt of Movement", Total: 20},
				{Type: "Passive", Name: "Bright Eyes", Found: "OnyxRing, SolakianAmulet", Total: 20},
				{Type: "Passive", Name: "Vim", Found: "Bonestone", Total: 20},
				{Type: "Passive", Name: "STR+1", Found: "FireOpal", Total: 15},
				{Type: "Passive", Name: "STR+2", Found: "Ruby", Total: 30},
				{Type: "Passive", Name: "VIT+1", Found: "Jade", Total: 15},
				{Type: "Passive", Name: "VIT+2", Found: "Emerald", Total: 30},
				{Type: "Passive", Name: "SPR+1", Found: "Aquamarine", Total: 15},
				{Type: "Passive", Name: "SPR+2", Found: "Sapphire", Total: 30},
				{Type: "Passive", Name: "AGL+1", Found: "Topaz", Total: 15},
				{Type: "Passive", Name: "AGL+2", Found: "Boots of Celerity", Total: 30},
				{Type: "Passive", Name: "Resist AETHER", Found: "Turquoise", Total: 50},
				{Type: "Passive", Name: "Rainbow Aura Lv.1", Found: "Rainbow Disc", Total: 50},
				{Type: "Passive", Name: "SOS Regen", Found: "Kind Star", Total: 20},
				{Type: "Passive", Name: "SOS Berserk", Found: "Horned Helm", Total: 10},
				{Type: "Passive", Name: "EXP+20%", Found: "Candriathope", Total: 40},
				{Type: "Passive", Name: "Double AP", Found: "EveningStar", Total: 200},
				{Type: "Passive", Name: "Double Gold", Found: "Regal Crown", Total: 100},
				{Type: "Passive", Name: "Loot Finder Lv.1", Found: "Lucky Coin", Total: 25}
			]
		}
	}
}